### ISSUE TITLE
About fenrich input qtl file

### ISSUE THREAD

**Issue by zhangpicb** [NLykoskoufis/fenrichcpp#8]
Dear @NLykoskoufis 

Thanks for the great tool!

About the input file used ,QTLTools format file 
https://github.com/NLykoskoufis/fenrichcpp/blob/97533f723835978308bac9ecd2687de560f94bb9/README.md?plain=1#L97

I used fastQTL,GTEx format,like these

```
gene_id variant_id      tss_distance    ma_samples      ma_count        maf     pval_nominal    slope   slope_se
```
And I find these files without ```dummy``` column and so on,
could I order my file column like QTLTools format file ,and``dummy``` column content use 0 
I don't know the result will be OK or not?

Thanks in advanced!

**Comment by NLykoskoufis** [comment]
Hi!, 

Thanks for giving the tool a try! As long as you provide the columns in the same order as for QTLtools it should work. For this particular file, the tool only uses the snp_id, snp_start, snp_end and dist_phe_var columns, the rest can be 0s or dots it should not matter. 

Hope it helps!

**Comment by zhangpicb** [comment]
Dear @NLykoskoufis 

Thanks for your quick reply!

It doesn't work. On step 2,I got the error message
```
Functional enrichment for QTL variants
 * Authors : Nikolaos M.R. LYKOSKOUFIS
 * Contact : nikolaos.lykoskoufis@unige.ch
 * Version : version 1.0

FUNCTIONAL ENRICHMENT ANALYSIS
Performing functional enrichment
 * Random variants: 100
 * Window size    : 2500
 * MAF window     : 0.02
 * seed           : 12345
 * Reading [null_variantFile.txt.gz]
Read 0 lines
Read 1000000 lines
Read 2000000 lines
Read 3000000 lines
Read 4000000 lines
Read 4818532 null variants.
 * Reading [EP.significant.txt.gz]
Segmentation fault (core dumped)

```
I transformed my file from this format to QTLtools format

My file
```
variant_id      gene_id tss_distance    ma_samples      ma_count        maf     pval_nominal    slope   slope_se        pval_nominal_threshold  min_pval_nominal        pval_beta
chr1_798618_C_T_b38     ENSG00000228794.8       -26520  23      24      0.129032        1.18466e-05     -0.54974        0.115709        2.42072e-05     8.49789e-10     1.48075e-06
chr1_798662_G_A_b38     ENSG00000228794.8       -26476  23      24      0.129032        1.18466e-05     -0.54974        0.115709        2.42072e-05     8.49789e-10     1.48075e-06
chr1_799111_T_C_b38     ENSG00000228794.8       -26027  23      24      0.129032        1.18466e-05     -0.54974        0.115709        2.42072e-05     8.49789e-10     1.48075e-06
```

QTLTools format,19 columns

```
ENSG00000228794.8 0 0 0 0 0 -26520 chr1_798618_C_T_b38 chr1 798618 798618 0 0 0 0 0 0 0 0
ENSG00000228794.8 0 0 0 0 0 -26476 chr1_798662_G_A_b38 chr1 798662 798662 0 0 0 0 0 0 0 0
ENSG00000228794.8 0 0 0 0 0 -26027 chr1_799111_T_C_b38 chr1 799111 799111 0 0 0 0 0 0 0 0

```

Thanks in advanced!

**Comment by NLykoskoufis** [comment]
Hi @zhangpicb, 

Your eQTL file should have a header line. Also, fenrich requires that eQTL files should be space separated. Is it the case for yours? Sorry this is not very clear maybe in the README. If your file is already space separated then, in order for me to debug what is going on, I would need you to provide me if possible a small chunk of the files your are providing to `fenrich` for me to see what is going on.. 

Hope that helps..
Cheers, 
Nikos

**Comment by zhangpicb** [comment]
Dear @NLykoskoufis 

Thanks for your quick reply!

https://github.com/qtltools/qtltools/tree/master/example_files QTLtools example data could use fenrich.But ```results.genes.full.txt.gz``` without header.

```
fenrich null   --vcf genotypes.chr22.vcf.gz --bed  genes.50percent.chr22.bed.gz --qtl results.genes.full.txt.gz  --out  null_variantFile.txt.gz
fenrich enrich \
  --null null_variantFile.txt.gz \
  --phen TFs.encode.bed.gz \
  --qtl results.genes.full.txt.gz \
  --out qtlTFenrichment.txt \
  --random_var 100 \
  --window_size 2500 \
  --maf_window 0.02
```

The result
```
cat qtlTFenrichment.txt
A       B       C       D
2601    2276    18578   17488
```

**Comment by zhangpicb** [comment]
Dear @NLykoskoufis 

I make fenrich input eQTL files have 1 SNP per gene.It works. 
If one gene have 2 or more eQTLs,the error happens.
But that sounds unrealistic,some genes do have 2 or more eQTLs.

**Comment by NLykoskoufis** [comment]
Hi @zhangpicb, 

I apologise for the delay. You are right, this sounds unrealistic. There is something weird because on my side, everything works fine even when genes have multiple eQTLs.  Maybe if you could provide your vcf and qtl results files for the genes it fails I can have a closer look to what happens :/

**Comment by zhangpicb** [comment]
Hi @NLykoskoufis 

Thanks for your reply!The problem is solved!

Thanks again!
